---
- name: Deploy Mini Web App Container
  hosts: localhost
  become: true

  tasks:
    - name: Pull latest mini-app image
      docker_image:
        name: my-mini-app
        source: pull
      ignore_errors: true

    - name: Stop existing mini-app container if exists
      docker_container:
        name: mini-app
        state: stopped
      ignore_errors: true

    - name: Remove existing mini-app container if exists
      docker_container:
        name: mini-app
        state: absent
      ignore_errors: true

    - name: Run mini-app container
      docker_container:
        name: mini-app
        image: my-mini-app
        state: started
        restart_policy: always
        ports:
          - "8080:8080"
        env:
          APP_VERSION: "1.0.1"
