---
- name: "Install Docker Engine on Target Servers"
  hosts: web
  become: true

  tasks:
    - name: "1. Install prerequisite packages"
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
        update_cache: yes

    - name: "2. Add Docker's official GPG key"
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: "3. Add Docker repository"
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

    - name: "4. Install Docker Engine"
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
        update_cache: yes

    - name: "5. Ensure Docker service is started and enabled"
      service:
        name: docker
        state: started
        enabled: yes